version: "3"

networks:
  backend:

services:
  db:
    image: postgres:latest
    ports:
      - 5678:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "db-admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "reasoneat"
    networks:
      - backend