version: "3"

networks:
  backend:

services:
  db:
    image: postgres:latest
    ports:
      - 5678:5432
    environment:
      POSTGRES_USER: "reasoneat_dba"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "reasoneat"
    networks:
      - backend