spring:
  datasource:
    url: jdbc:postgresql://localhost:5678/reasoneat
    username: reasoneat_dba
    password: password

  #drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true